---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ influxdb_dependencies }}"
    state: present
    update_cache: true

- name: Add InfluxData's key
  ansible.builtin.apt_key:
    state: present
    url: "{{ influxdb_signing_key }}"

- name: Manage InfluxData APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ influxdb_repositories }}"

- name: Ensure InfluxDB packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ influxdb_package_state }}"
    update_cache: true
  loop: "{{ influxdb_packages }}"