---
- name: Disable password login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    insertafter: '^#PasswordAuthentication '
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  when: disable_password_login
  notify: Restart ssh server