---
- name: Ensure Nftables is installed
  ansible.builtin.apt:
    pkg:
      - nftables
    update_cache: true

- name: Update Nftables configuration
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    group: root
    owner: root
  notify: Reload firewall services

- name: Enable nftables
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: started